Homework3 PR
tarasandrusiv/AQA_Python_T pull request #3
Opened 2023-12-10 11:26 UTC by tarasandrusiv

2023-12-10 20:25 UTC, antohaUa requested changes
Fixes required

2023-12-10 20:25 UTC, antohaUa commented on homework3.py
> +"""Homework3."""
Within docstring better to put task description too.

2023-12-10 20:25 UTC, antohaUa commented on homework3.py
> +norway_text_format_method = """Automatisering akselererer {0}yeblikket da roboter
Three quotes construction acceptable - but try to find way how to use the same string with single quoting and bypass linter e501 errors about string length

2023-12-10 20:25 UTC, antohaUa commented on homework3.py
> +print(f"""Automatisering akselererer {first_var}yeblikket da roboter
Here better text to place into variable first and then just print this variable.
Also please find way how to avoid thee quotes and use single quoting

2023-12-10 22:20 UTC, tarasandrusiv commented on homework3.py
> +norway_text_format_method = """Automatisering akselererer {0}yeblikket da roboter
still couldn't find the way to fix this.

2023-12-10 22:20 UTC, tarasandrusiv commented on homework3.py
> +print(f"""Automatisering akselererer {first_var}yeblikket da roboter
done

2023-12-10 22:20 UTC, tarasandrusiv commented on homework3.py
> +"""Homework3."""
done

2023-12-16 14:27 UTC, tarasandrusiv commented on homework3.py
> +norway_text_format_method = """Automatisering akselererer {0}yeblikket da roboter
fixed

2023-12-16 21:29 UTC, tarasandrusiv commented
@antohaUa please review  my pr once again

2023-12-23 10:08 UTC, merged